name: Deploy Landing Page to S3 & CloudFront

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  deploy:
    name: Build & Deploy Landing Page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Vite App
        run: |
          npm run build

      - name: Deploy static assets to S3
        run: |
          aws s3 sync dist/ s3://embedcraft-production-landing-bucket --delete --region ap-south-1

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E3M8FDMP3HW5BN --paths "/*" --region us-east-1
